modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Low-Drag-MC/Shimmer/issues"

[[mods]]
modId="shimmer"
version="${file.jarVersion}"
displayName="Shimmer"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="assets/shimmer/icon.png"
credits="zomb_676"
authors="KilaBash"
description='''
Shimemr
'''

[[dependencies.shimmer]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shimmer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
