name: build

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    
    - name: Grant execute permission for gradle
      run: chmod +x gradlew
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v4
      with:
        arguments: build
    
    - name: Upload Jars
      uses: actions/upload-artifact@v3
      with:
        name: Shimmer
        path: |
          Fabric/build/libs
          Forge/build/libs
